services:
  mysqldb:
      image: mysql:8.0.19
      container_name: mysql
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: almacen
        MYSQL_PASSWORD: root
      ports:
        - "3306:3306"
        - "33060:33060"
      # working_dir: /var/lib/mysql
      # volumes:
      #   - "./mysql:/var/lib/mysql:rw"
      